import { db } from "@/lib/firebase/config";
import { collection, addDoc } from "firebase/firestore";

export function seedDatabase(firebase: any) {
    function getUUID() {
        return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
            const piece = (Math.random() * 16) | 0;
            const elem = c === "x" ? piece : (piece & 0x3) | 0x8;
            return elem.toString(16);
        });
    }

    // Product data
    const products = [
        {
            id: getUUID(),
            name: "Wireless Headphones",
            description: "Noise-cancelling over-ear headphones",
            fullDescription:
                "Premium wireless headphones with 30-hour battery life and active noise cancellation.",
            price: 129.99,
            originalPrice: 159.99,
            imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",
            category: "Electronics",
            categoryId: "cat1",
            inStock: true,
            onSale: true,
            featured: true,
            rating: 4.7,
            reviewCount: 2,
            createdAt: new Date(),
            specifications: [
                { name: "Battery Life", value: "30 hours" },
                { name: "Connectivity", value: "Bluetooth 5.1" },
            ],
            reviews: [
                {
                    userId: "user1",
                    userName: "John Doe",
                    rating: 5,
                    comment: "Fantastic sound quality!",
                    date: new Date("2025-01-10"),
                },
                {
                    userId: "user2",
                    userName: "Jane Smith",
                    rating: 4,
                    comment: "Good, but a bit pricey.",
                    date: new Date("2025-02-15"),
                },
            ],
        },
        {
            id: getUUID(),
            name: "Smart Watch",
            description: "Fitness tracker with heart rate monitor",
            price: 89.99,
            imageUrl: "https://images.unsplash.com/photo-1523275339254-cc1774077256",
            category: "Wearables",
            categoryId: "cat2",
            inStock: true,
            rating: 4.3,
            reviewCount: 3,
            createdAt: new Date(),
            specifications: [
                { name: "Display", value: '1.4" OLED' },
                { name: "Water Resistance", value: "5 ATM" },
            ],
            reviews: [
                {
                    userId: "user3",
                    userName: "Alex Brown",
                    rating: 4,
                    comment: "Great for workouts!",
                    date: new Date("2025-03-01"),
                },
                {
                    userId: "user4",
                    userName: "Emily White",
                    rating: 5,
                    comment: "Love the design.",
                    date: new Date("2025-03-05"),
                },
                {
                    userId: "user5",
                    userName: "Mike Green",
                    rating: 3,
                    comment: "Battery life could be better.",
                    date: new Date("2025-03-10"),
                },
            ],
        },
        {
            id: getUUID(),
            name: "Leather Jacket",
            description: "Classic black leather jacket",
            price: 199.99,
            imageUrl: "https://images.unsplash.com/photo-1520639888713-8b759eb681a6",
            category: "Clothing",
            categoryId: "cat3",
            inStock: false,
            rating: 4.9,
            reviewCount: 0,
            createdAt: new Date(),
        },
        {
            id: getUUID(),
            name: "Gaming Laptop",
            description: "High-performance laptop for gaming",
            price: 1499.99,
            imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
            category: "Electronics",
            categoryId: "cat1",
            inStock: true,
            rating: 4.8,
            reviewCount: 2,
            createdAt: new Date(),
            specifications: [
                { name: "Processor", value: "Intel i7" },
                { name: "RAM", value: "16GB" },
                { name: "GPU", value: "NVIDIA RTX 3060" },
            ],
            reviews: [
                {
                    userId: "user6",
                    userName: "Chris Lee",
                    rating: 5,
                    comment: "Runs games smoothly!",
                    date: new Date("2025-02-20"),
                },
                {
                    userId: "user7",
                    userName: "Sara Kim",
                    rating: 4,
                    comment: "Great, but heavy.",
                    date: new Date("2025-02-25"),
                },
            ],
        },
        {
            id: getUUID(),
            name: "Running Shoes",
            description: "Lightweight running shoes with cushioning",
            price: 79.99,
            imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
            category: "Footwear",
            categoryId: "cat4",
            inStock: true,
            rating: 4.5,
            reviewCount: 2,
            createdAt: new Date(),
            reviews: [
                {
                    userId: "user8",
                    userName: "Tom Wilson",
                    rating: 5,
                    comment: "Super comfortable!",
                    date: new Date("2025-01-20"),
                },
                {
                    userId: "user9",
                    userName: "Lisa Chen",
                    rating: 4,
                    comment: "Good grip on trails.",
                    date: new Date("2025-01-25"),
                },
            ],
        },
        {
            id: getUUID(),
            name: "Coffee Maker",
            description: "Automatic drip coffee maker",
            price: 49.99,
            imageUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93",
            category: "Appliances",
            categoryId: "cat5",
            inStock: true,
            rating: 4.2,
            reviewCount: 0,
            createdAt: new Date(),
        },
        {
            id: getUUID(),
            name: "Backpack",
            description: "Water-resistant travel backpack",
            price: 59.99,
            originalPrice: 79.99,
            imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62",
            category: "Accessories",
            categoryId: "cat6",
            inStock: true,
            onSale: true,
            rating: 4.6,
            reviewCount: 0,
            createdAt: new Date(),
        },
        {
            id: getUUID(),
            name: "Desk Lamp",
            description: "LED desk lamp with adjustable brightness",
            price: 29.99,
            imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
            category: "Home",
            categoryId: "cat7",
            inStock: true,
            rating: 4.4,
            reviewCount: 0,
            createdAt: new Date(),
        },
        {
            id: getUUID(),
            name: "Bluetooth Speaker",
            description: "Portable waterproof speaker",
            price: 39.99,
            imageUrl: "https://images.unsplash.com/photo-1542187166-1b1e2a6e6f43",
            category: "Electronics",
            categoryId: "cat1",
            inStock: true,
            rating: 4.5,
            reviewCount: 3,
            createdAt: new Date(),
            reviews: [
                {
                    userId: "user10",
                    userName: "Rachel Patel",
                    rating: 5,
                    comment: "Loud and clear!",
                    date: new Date("2025-03-15"),
                },
                {
                    userId: "user11",
                    userName: "David Ortiz",
                    rating: 4,
                    comment: "Perfect for the beach.",
                    date: new Date("2025-03-20"),
                },
                {
                    userId: "user12",
                    userName: "Kelly Nguyen",
                    rating: 5,
                    comment: "Battery lasts forever!",
                    date: new Date("2025-03-22"),
                },
            ],
        },
        {
            id: getUUID(),
            name: "Sunglasses",
            description: "Polarized aviator sunglasses",
            price: 34.99,
            imageUrl: "https://images.unsplash.com/photo-1572635196237-14b3f281503f",
            category: "Accessories",
            categoryId: "cat6",
            inStock: true,
            rating: 4.7,
            reviewCount: 0,
            createdAt: new Date(),
        },
        {
            id: getUUID(),
            name: "Yoga Mat",
            description: "Non-slip yoga mat with extra cushioning",
            price: 24.99,
            imageUrl: "https://images.unsplash.com/photo-1601925267898-c5a891e9b79c",
            category: "Fitness",
            categoryId: "cat8",
            inStock: true,
            rating: 4.3,
            reviewCount: 0,
            createdAt: new Date(),
        },
        {
            id: getUUID(),
            name: "Electric Kettle",
            description: "Stainless steel electric kettle",
            price: 39.99,
            imageUrl: "https://images.unsplash.com/photo-1571772801628-7e57d0e3f498",
            category: "Appliances",
            categoryId: "cat5",
            inStock: true,
            rating: 4.6,
            reviewCount: 0,
            createdAt: new Date(),
        },
        {
            id: getUUID(),
            name: "Denim Jeans",
            description: "Slim-fit blue denim jeans",
            price: 69.99,
            imageUrl: "https://images.unsplash.com/photo-1542272604-787c3835535d",
            category: "Clothing",
            categoryId: "cat3",
            inStock: true,
            rating: 4.4,
            reviewCount: 0,
            createdAt: new Date(),
        },
        {
            id: getUUID(),
            name: "Wireless Mouse",
            description: "Ergonomic wireless mouse",
            price: 19.99,
            imageUrl: "https://images.unsplash.com/photo-1613141411240-085aca895a15",
            category: "Electronics",
            categoryId: "cat1",
            inStock: true,
            rating: 4.2,
            reviewCount: 0,
            createdAt: new Date(),
        },
        {
            id: getUUID(),
            name: "Ceramic Mug Set",
            description: "Set of 4 ceramic coffee mugs",
            price: 29.99,
            imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
            category: "Home",
            categoryId: "cat7",
            inStock: true,
            rating: 4.5,
            reviewCount: 0,
            createdAt: new Date(),
        },
    ];

    // Seed the products collection
    products.forEach(async (product) => {
        await addDoc(collection(db, "products"), {
            ...product,
            createdAt: product.createdAt.toISOString(),
            reviews: product.reviews?.map((review) => ({
                ...review,
                date: review.date.toISOString(),
            })),
        });
    });
}

console.log("Database seeded with 15 products");
